// packages/deploy-core/src/errors.ts

export const DEPLOY_CORE_ERROR_CODES = {
  ZIP_OPEN_FAILED: "ZIP_OPEN_FAILED",
  ZIP_ENTRY_PATH_TRAVERSAL: "ZIP_ENTRY_PATH_TRAVERSAL",
  ZIP_ENTRY_ABSOLUTE_PATH: "ZIP_ENTRY_ABSOLUTE_PATH",
  ZIP_ENTRY_WINDOWS_DRIVE_PATH: "ZIP_ENTRY_WINDOWS_DRIVE_PATH",
  ZIP_ENTRY_NUL_BYTE: "ZIP_ENTRY_NUL_BYTE",
  ZIP_ENTRY_UNSUPPORTED_TYPE: "ZIP_ENTRY_UNSUPPORTED_TYPE",
  ZIP_ENTRY_SYMLINK: "ZIP_ENTRY_SYMLINK",
  ZIP_ENTRY_DUPLICATE_PATH: "ZIP_ENTRY_DUPLICATE_PATH",
  ZIP_TOO_MANY_FILES: "ZIP_TOO_MANY_FILES",
  ZIP_SINGLE_FILE_TOO_LARGE: "ZIP_SINGLE_FILE_TOO_LARGE",
  ZIP_TOTAL_SIZE_TOO_LARGE: "ZIP_TOTAL_SIZE_TOO_LARGE",
  ZIP_EXTRACT_FAILED: "ZIP_EXTRACT_FAILED",
  MANIFEST_HASH_FAILED: "MANIFEST_HASH_FAILED",
} as const;

export type DeployCoreErrorCode = (typeof DEPLOY_CORE_ERROR_CODES)[keyof typeof DEPLOY_CORE_ERROR_CODES];

export class DeployCoreError extends Error {
  constructor(
    public code: string,
    public details?: Record<string, unknown>,
  ) {
    super(code);
    this.name = "DeployCoreError";
  }
}
